version: 2

jobs:
  "Test":
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/xebia-france/xebikart-state-api

    steps:
      - checkout
      - run:
          name: Test
          command: make test

workflows:
  version: 2
  full:
    jobs:
      - "Test"
